BEGIN;

DROP TABLE IF EXISTS users, posts, comments CASCADE;

CREATE TABLE IF NOT EXISTS users(
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL,
  password VARCHAR(100) NOT NULL,
  img_url TEXT
);

CREATE TABLE IF NOT EXISTS posts(
  id SERIAL PRIMARY KEY,
  post_text TEXT NOT NULL,
  post_img TEXT,
  likes INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments(
  id SERIAL PRIMARY KEY,
  comment_text TEXT NOT NULL,
  likes INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(id),
  post_id INT,
  FOREIGN KEY (post_id) REFERENCES posts(id)
);

COMMIT;